### ISSUE TITLE
Kitty terminal Missing

### ISSUE THREAD

**Issue by PardesiCat** [JonathanSanfilippo/Archmain#21]
it would be great if you add kitty terminal in install.sh (bash)

[Kitty-Terminal](https://sw.kovidgoyal.net/kitty/)

**Comment by JonathanSanfilippo** [comment]
we are working on version 300
should be able to support these terminals
'gnome-terminal', 'konsole', 'xfce4-terminal', 'kgx', 'lxterminal', 'alacritty',
                  'mate-terminal', 'deepin-terminal', 'qterminal', 'terminator', 'tilix', 'xterm', 'rxvt',
                  'xfterm+', 'eterm', 'st', 'aterm', 'sakura', 'lilyterm', 'cool-retro-term', 'guake', 'kitty',
                  'yakuake'
